name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install babel
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Build the React app
        run: npm run build

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactapp:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reactapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (optional)
        uses: actions/checkout@v3

      - name: Log in to Azure with Username/Password
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_USERNAME }}
          client-secret: ${{ secrets.AZURE_PASSWORD }}
          tenant-id: c66b6765-b794-4a2b-84ed-845b341c086a  # Required if your account is part of multiple tenants

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Liftmate
          slot-name: production
          images: ${{ secrets.DOCKER_USERNAME }}/reactapp:latest
